### ISSUE TITLE
some guidance on running; cannot generate novel annotations

### ISSUE THREAD

**Issue by callumparr** [dewyman/TALON#39]
I was confused as to how to move through talon scripts. 

I downsampled my reads to 10e4, then mapped to hg38 using minimap2 with --MD flag included to generated > aln.sam 

I then used TranscriptClean but without -v or -j flags to error correct and output clean.sam 

Next I used this to initialize a talon db using the initialize script feeding in gencode.v29.annotation.gtf and --g hg38_build --a hg38_annot

Following this, I used talon.py script with the db, and config.csv pointing to clean.sam file and metadata. This gave and log_QC.txt file and update the hg38.db. 

Finally I ran the create_abundance_file_from_database and this gave me a .tsv file. 

However when I check the columns for exon and gene, I cannot find any unknown. Even with small number of reads would expect something? 

[example_head.xlsx](https://github.com/dewyman/TALON/files/3349695/example_head.xlsx)

**Comment by dewyman** [comment]
Hi Callum,
Thank you for your question. Have you checked the transcript novelty column? Novel genes are rather rare in the human data so I would not be too surprised not to have a novel gene in 10e4 reads.

**Comment by callumparr** [comment]
Sorry I was stupid and I scrolled all the way through the file I can see novel TALON annotations. Does the script some sort of sorting of the results? Based on annotations hits rather than the order of the reads in the sam file. 

Perhaps I see too many. I did run it through TranscriptClean but I ignored the splice site correction so it probably is better to do this.

**Comment by dewyman** [comment]
The abundance file does tend to list the known annotations first.

I would recommend looking at how many transcripts you get in each novelty category, and going from there. Without filtering the novel transcripts for reproducibility across multiple datasets, you might reasonably expect to get a higher rate of novelty in the output. If these are mainly incomplete splice matches (ISM) and novel in catalog (NIC) transcripts, then TranscriptClean splice site correction won't have a big impact since these transcripts contain known splice donors and acceptors- it is mainly targeted at fixing artifactual novel not in catalog (NNC) transcripts.

**Comment by dewyman** [comment]
Note: This script will plot the number of distinct transcript models detected for each novelty category, and the number of reads that were annotated to each novelty category:
https://github.com/dewyman/TALON-paper-2019/blob/master/analysis_scripts/plot_novelty_categories_from_abd_table.R

Here are instructions to run it:
```
Rscript plot_novelty_categories_from_abd_table.R --h
Options:
	--f=F
		TALON abundance file

	--datasets=DATASETS
		Optional: Comma-separated list of datasets to include. Default is to use all datasets in the file

	-o OUTDIR, --outdir=OUTDIR
		Output directory for plots and outfiles

	-h, --help
		Show this help message and exit
```
