### ISSUE TITLE
Running slowly on PBS/Torque

### ISSUE THREAD

**Issue by hasacat** [dewyman/TALON#41]
I was wondering if there is a faster way to run this on large SAM files (>30gb) - will there be a parallel version of TALON?

**Comment by dewyman** [comment]
It is somewhat difficult to parallelize the core functionality of TALON since the inputs are not independent of each other (i.e. each new transcript being processed needs to be compared to all previous transcripts), but I will certainly make an effort to do so in the future. Runtime is an important consideration.

**Comment by hasacat** [comment]
Yes, this makes sense - thanks. Could some level of parallel functionality be achieved by assuming that new transcripts only need to be compared to previous transcripts of the same chromosome (i.e. transcripts on different chromosomes are independent)? I've been splitting up the SAM file into different chromosomes and running TALON/TranscriptClean on each one independently to reduce the runtime, but maybe this could be an option for an internal process rather than a user-performed one.

**Comment by dewyman** [comment]
Yes, that is something we have though about doing in the past- we just haven't had the time/bandwidth to actually implement it yet.

**Comment by fairliereese** [comment]
Hi, in case you were still interested, @dewyman recently parallelized TALON and it is now blazing fast!

**Comment by hasacat** [comment]
awesome! great to hear 😃
