### ISSUE TITLE
talon_generate_report error

### ISSUE THREAD

**Issue by sgiannouk** [dewyman/TALON#53]
Hi there, 

I tried to run talon and everything run smoothly, but when I get to the point to run 'talon_generate_report', I got the following issue even though I have already installed all the necessary libraries in R.  

$ talon_generate_report
Loading required packages...
One of the required packages is missing.
Here's the original error message:
there is no package called ‘DBI’Error in theme_bw(base_family = "Helvetica", base_size = 18) :
  could not find function "theme_bw"
Calls: main ... custom_theme -> suppressMessages -> withCallingHandlers
Execution halted

I also couldn't find the exact arguments for running talon_generate_report. Is there somewhere in the documentation? 

Thank you in advance!

**Comment by dewyman** [comment]
Hello!
The talon_generate_report script is not in the documentation because it is something we started working on a while back, but didn't really develop into a production-ready feature. 

That said, based on the error you are getting, it looks like the script may be having problems loading the R packages DBI and ggplot2. To get the arguments for the script, you can run talon_generate_report -h. 

Best,
Dana

**Comment by sgiannouk** [comment]
Hi Dana, 

I see you are right, I was missing one package, but now it's working properly, Thanx!
One more question,  can you explain a bit more what is needed in the argument '--datasets'?

Greetings,
Stavros

**Comment by dewyman** [comment]
Hi Stavros, 

The datasets argument takes a comma-delimited list of the dataset names you would like to include. These would correspond to one or more dataset names from your config file.

Best,
Dana

**Comment by sgiannouk** [comment]
Great, thank you for your help! 

Greetings,
Stavros
